package CmmdcApp;


/**
* CmmdcApp/CmmdcOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cmmdc.idl
* Thursday, November 2, 2017 11:15:53 AM EET
*/

public interface CmmdcOperations 
{
  long cmmdc (long a, long b);
} // interface CmmdcOperations
