package CmmdcApp;


/**
* CmmdcApp/Cmmdc.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cmmdc.idl
* Thursday, November 2, 2017 11:15:53 AM EET
*/

public interface Cmmdc extends CmmdcOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Cmmdc
